### ISSUE TITLE
Why does the button of "Insert blocks" disappear when I use the branch of canary

### ISSUE THREAD

**Issue by WesternFastShooters** [pengx17/awesome-affine#14]
![button_disappear](https://github.com/toeverything/awesome-affine/assets/125524146/af88af05-3ac8-455f-b6c9-ff53a854eb97)

**Comment by WesternFastShooters** [comment]
![localhost_disappear](https://github.com/toeverything/awesome-affine/assets/125524146/c7a29c01-b9f9-4dc4-9939-b2d6e6816210)

**Comment by fourdim** [comment]
It's removed. You can type "/" for commands to insert blocks.
